///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DimmingDataLampStatus {
/*
{
  "auto_light": 1,
  "lamp_vector": 1,
  "power_rate": 250
}
*/

  int autoLight;
  int lampVector;
  int powerRate;

  DimmingDataLampStatus({
    this.autoLight,
    this.lampVector,
    this.powerRate,
  });
  DimmingDataLampStatus.fromJson(Map<String, dynamic> json) {
    autoLight = json["auto_light"]?.toInt();
    lampVector = json["lamp_vector"]?.toInt();
    powerRate = json["power_rate"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["auto_light"] = autoLight;
    data["lamp_vector"] = lampVector;
    data["power_rate"] = powerRate;
    return data;
  }
}

class DimmingData {
/*
{
  "auto_alarm": 1,
  "ctrl_state": 1,
  "detail": "",
  "lamp_count": 2,
  "lamp_status": [
    {
      "auto_light": 1,
      "lamp_vector": 1,
      "power_rate": 250
    }
  ],
  "latitude": "29.22333333",
  "longitude": "119",
  "report_cycle": 25,
  "report_reply": 0,
  "status": 1
}
*/

  int autoAlarm;
  int ctrlState;
  int lampCount;
  List<DimmingDataLampStatus> lampStatus;
  String latitude;
  String longitude;
  int reportCycle;
  int reportReply;
  int status;

  DimmingData({
    this.autoAlarm,
    this.ctrlState,
    this.lampCount,
    this.lampStatus,
    this.latitude,
    this.longitude,
    this.reportCycle,
    this.reportReply,
    this.status,
  });
  DimmingData.fromJson(Map<String, dynamic> json) {
    autoAlarm = json["auto_alarm"]?.toInt();
    ctrlState = json["ctrl_state"]?.toInt();
    lampCount = json["lamp_count"]?.toInt();
    if (json["lamp_status"] != null) {
      var v = json["lamp_status"];
      var arr0 = List<DimmingDataLampStatus>();
      v.forEach((v) {
        arr0.add(DimmingDataLampStatus.fromJson(v));
      });
      lampStatus = arr0;
    }
    latitude = json["latitude"]?.toString();
    longitude = json["longitude"]?.toString();
    reportCycle = json["report_cycle"]?.toInt();
    reportReply = json["report_reply"]?.toInt();
    status = json["status"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["auto_alarm"] = autoAlarm;
    data["ctrl_state"] = ctrlState;
    data["lamp_count"] = lampCount;
    if (lampStatus != null) {
      var v = lampStatus;
      var arr0 = List();
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data["lamp_status"] = arr0;
    }
    data["latitude"] = latitude;
    data["longitude"] = longitude;
    data["report_cycle"] = reportCycle;
    data["report_reply"] = reportReply;
    data["status"] = status;
    return data;
  }
}


